# Generated by Django 2.2.6 on 2019-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinformation',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
